name: tests

on:
  # Trigger the workflow on push or pull request on main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run cron job every month, https://crontab.guru/every-month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  # This job tests that the CC works
  test-cc-and-jb-build:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Use the default CC
    - name: Check black style
      run: |
        black ./ --check
    # Run tests
    - name: Pytest tests
      run: |
        pytest
    # Use default CC
    - name: Cookiecutter no GHA
      run: |
        cookiecutter . --no-input --overwrite-if-exists include_ci=no 
    # Install requirements.txt
    - name: Install requirements
      run: |
        pip install -r my_book/requirements.txt
    # Build the example book
    - name: Build book
      run: |
        jupyter-book build my_book/my_book/
    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "my_book/my_book/_build/html"
    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2